name: Super Linter

on: push

jobs:
  python-linting-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  
